### ISSUE TITLE
Detect all paths in 17eyes!

### ISSUE THREAD

**Issue by Rivendall** [17eyes/17eyes#34]
Hello
I research about static code analyzers. I want to understand, how to work them. Specially, Parse after analysis and detect patch in php code. I know, php parser not be able to recognize include, require and etc expression. I want to know, how dose your program recognize path? Or is it need?
Did you use any library or tools? or did you develop this part in your app?
How dose 17eye detect all paths in php code?
How about other tools?
Dose it need special libraries?

Thank you.

**Comment by akat1** [comment]
Oh, that's extremely difficult question, 17eyes is for now dumb so it doesn't do anything in regard to require or include. I suggest you to check what RIPS does. Good luck! :)

**Comment by Rivendall** [comment]
Thank you.
