### ISSUE TITLE
Array and strings literals dereferencing 

### ISSUE THREAD

**Issue by 17eyes** [17eyes/17eyes#5]
As http://php.net/manual/en/migration55.new-features.php says:

[...]
Array and string literals can now be dereferenced directly to access individual elements and characters:

<?php
echo 'Array dereferencing: ';
echo [1, 2, 3][0];
echo "\n";

echo 'String dereferencing: ';
echo 'PHP'[0];
echo "\n";
?>
[...]

**Comment by akat1** [comment]
We already support this. (We even allow number literals derefencing ;-)).
